-- MySQL Script generated by MySQL Workbench
-- Tue Jun  1 02:16:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_cinema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_cinema` ;

-- -----------------------------------------------------
-- Schema bd_cinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_cinema` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci ;
USE `bd_cinema` ;

-- -----------------------------------------------------
-- Table `bd_cinema`.`cinema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_cinema`.`cinema` ;

CREATE TABLE IF NOT EXISTS `bd_cinema`.`cinema` (
  `id_cinema` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cinema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cinema`.`sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_cinema`.`sala` ;

CREATE TABLE IF NOT EXISTS `bd_cinema`.`sala` (
  `cinema_id` INT NOT NULL,
  `numero` INT NOT NULL,
  `capacidad` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`cinema_id`, `numero`),
  CONSTRAINT `fk_sala_cinema`
    FOREIGN KEY (`cinema_id`)
    REFERENCES `bd_cinema`.`cinema` (`id_cinema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cinema`.`asiento_sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_cinema`.`asiento_sala` ;

CREATE TABLE IF NOT EXISTS `bd_cinema`.`asiento_sala` (
  `sala_cinema_id` INT NOT NULL,
  `sala_numero` INT NOT NULL,
  `fila` CHAR(1) NOT NULL,
  `posicion` INT(2) NOT NULL,
  `disponible` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`sala_cinema_id`, `sala_numero`, `fila`, `posicion`),
  CONSTRAINT `fk_asiento_sala`
    FOREIGN KEY (`sala_cinema_id` , `sala_numero`)
    REFERENCES `bd_cinema`.`sala` (`cinema_id` , `numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cinema`.`pelicula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_cinema`.`pelicula` ;

CREATE TABLE IF NOT EXISTS `bd_cinema`.`pelicula` (
  `id_pelicula` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `poster_path` VARCHAR(45) NOT NULL,
  `movie_data` LONGTEXT NOT NULL,
  PRIMARY KEY (`id_pelicula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cinema`.`funcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_cinema`.`funcion` ;

CREATE TABLE IF NOT EXISTS `bd_cinema`.`funcion` (
  `sala_cinema_id` INT NOT NULL,
  `sala_numero` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `pelicula_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sala_cinema_id`, `sala_numero`, `fecha`),
  INDEX `fk_funcion_pelicula_idx` (`pelicula_id` ASC),
  CONSTRAINT `fk_funcion_sala`
    FOREIGN KEY (`sala_cinema_id` , `sala_numero`)
    REFERENCES `bd_cinema`.`sala` (`cinema_id` , `numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcion_pelicula`
    FOREIGN KEY (`pelicula_id`)
    REFERENCES `bd_cinema`.`pelicula` (`id_pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cinema`.`asiento_funcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_cinema`.`asiento_funcion` ;

CREATE TABLE IF NOT EXISTS `bd_cinema`.`asiento_funcion` (
  `funcion_sala_cinema_id` INT NOT NULL,
  `funcion_sala_numero` INT NOT NULL,
  `funcion_fecha` DATETIME NOT NULL,
  `fila` CHAR(1) NOT NULL,
  `posicion` INT(2) NOT NULL,
  `ocupado` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`funcion_sala_cinema_id`, `funcion_sala_numero`, `funcion_fecha`, `fila`, `posicion`),
  CONSTRAINT `fk_asiento_funcion`
    FOREIGN KEY (`funcion_sala_cinema_id` , `funcion_sala_numero` , `funcion_fecha`)
    REFERENCES `bd_cinema`.`funcion` (`sala_cinema_id` , `sala_numero` , `fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cinema`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_cinema`.`cliente` ;

CREATE TABLE IF NOT EXISTS `bd_cinema`.`cliente` (
  `id_cliente` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `tarjeta_pago` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cinema`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_cinema`.`factura` ;

CREATE TABLE IF NOT EXISTS `bd_cinema`.`factura` (
  `seq_factura` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `cliente_id` VARCHAR(45) NOT NULL,
  `tarjeta_pago` VARCHAR(45) NULL,
  PRIMARY KEY (`seq_factura`),
  INDEX `fk_factura_cliente_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_factura_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `bd_cinema`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cinema`.`tiquete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_cinema`.`tiquete` ;

CREATE TABLE IF NOT EXISTS `bd_cinema`.`tiquete` (
  `id_tiquete` INT NOT NULL AUTO_INCREMENT,
  `factura_seq` INT NOT NULL,
  `asiento_funcion_sala_cinema_id` INT NOT NULL,
  `asiento_funcion_sala_numero` INT NOT NULL,
  `asiento_funcion_fecha` DATETIME NOT NULL,
  `asiento_funcion_fila` CHAR(1) NOT NULL,
  `asiento_funcion_posicion` INT(2) NOT NULL,
  `monto` DOUBLE NOT NULL,
  PRIMARY KEY (`id_tiquete`),
  INDEX `fk_tiquete_factura_idx` (`factura_seq` ASC),
  INDEX `fk_tiquete_asiento_funcion_idx` (`asiento_funcion_sala_cinema_id` ASC, `asiento_funcion_sala_numero` ASC, `asiento_funcion_fecha` ASC, `asiento_funcion_fila` ASC, `asiento_funcion_posicion` ASC),
  CONSTRAINT `fk_tiquete_factura`
    FOREIGN KEY (`factura_seq`)
    REFERENCES `bd_cinema`.`factura` (`seq_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tiquete_asiento_funcion`
    FOREIGN KEY (`asiento_funcion_sala_cinema_id` , `asiento_funcion_sala_numero` , `asiento_funcion_fecha` , `asiento_funcion_fila` , `asiento_funcion_posicion`)
    REFERENCES `bd_cinema`.`asiento_funcion` (`funcion_sala_cinema_id` , `funcion_sala_numero` , `funcion_fecha` , `fila` , `posicion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cinema`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_cinema`.`usuario` ;

CREATE TABLE IF NOT EXISTS `bd_cinema`.`usuario` (
  `id_usuario` VARCHAR(45) NOT NULL,
  `cliente_id` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `rol` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_cliente_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_usuario_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `bd_cinema`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
